# 页面默认前缀目录
application:
  name: 系统名称
  code: systemName
#服务器配置
server:
  #端口
  port: 8080
  #访问的项目名
  servlet:
    context-path: /${application.code}
  #tomcat配置
  tomcat:
    port-header: HEAD,PUT,DELETE,OPTIONS,TRACE,COPY,SEARCH,PROPFIND #禁用http不安全请求
  uri-encoding: utf-8
#spring配置
spring:
  #使用的对应环境配置文件
  profiles:
    active: dev
  #输出信息配置
  output:
    ansi:
      enabled: DETECT
  #thymeleaf模板配置 (前后端分离后，如果前端页面和后端接口整合一起部署需要配置，如果前端页面和后端接口分开部署不需要这部分的配置)
  thymeleaf:
    cache: false
    check-template: false
    # 在构建URL时预先查看名称的前缀（前端静态页面的路径）
    prefix: classpath:/dist/
    encoding: UTF-8
  #json格式配置
  jackson:
    serialization:
       #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: always
    time-zone: GMT+8
  #java持久化配置
  jpa:
    database: mysql
    show-sql: true
    hibernate:
     ddl-auto: update
    naming:
      strategy: org.hibernate.cfg.ImprovedNamingStrategy
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      name: Resource-master
      initial-size: 2
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      check_data_source_thread_times: 60000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,config,log4j2
      use-global-data-source-stat: true
      web-stat-filter:
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        login-username: druid
        login-password: druid
      connection-properties: config.decrypt=false;config.decrypt.key=${public-key}
      filter:
        config:
          enabled: true

# Mybatis
mybatis:
  #一般对应我们的实体类所在的包，这个时候会自动取对应包中不包括包名的简单类名作为包括包名的别名。多个package之间可以用逗号或者分号等来进行分隔
  #在mapper中配置了resultMap可以不管
  #type-aliases-package: com.base.demo.model.*.entity
  #配置mapper位置
  mapper-locations : mappers/**/*.xml

#分页的配置
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  reasonable: true